name: votey
description: A new Flutter project.
publish_to: 'none' 

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.1
  carousel_slider: ^4.0.0
  shared_preferences: ^2.0.13
  rive: ^0.8.1
  uuid: ^3.0.6
  firebase_core: ^1.13.1
  firebase_auth: ^3.3.11
  cloud_firestore: ^3.1.10
  flutter_svg: ^1.0.3
  camera: ^0.9.4+16
  flutter_native_splash: ^2.1.1
  firebase_remote_config: ^2.0.2
  firebase_analytics: ^9.1.2
  firebase_messaging: ^11.2.11
  awesome_notifications: ^0.6.21

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4


flutter:
  uses-material-design: true
  assets:
   - assets/images/
   - assets/loadings/
  fonts:
   - family: Nunito
     fonts:
       - asset: assets/fonts/Nunito.ttf
         weight: 400
         style: normal
         

